// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxmuvalqjrpdrtuxbeek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bXV2YWxxanJwZHJ0dXhiZWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjkwNDAsImV4cCI6MjA2NTI0NTA0MH0.-Ulxl_KuYN8hNrb2L4IBzhKKYLTug4B2lDkrrOkgbrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);